### Import libraries

In [2]:
import numpy as np
from fxpmath import Fxp
from utils import*

### Read matrices A and B from $\texttt{test\_case.txt}$
This file contains:

A:

2.54 4.31 3.15

1.01 0.0 5.74

6.84 3.21 3.17

B:

1.0 0 0

0 1.0 0

0 0 1.0

In [7]:
matrices = read_matrix("test_case.txt")
a = matrices['A']
b = matrices['B']

In [9]:
print("Matrix A is: ")
print(a)

Matrix A is: 
[[2.54 4.31 3.15]
 [1.01 0.   5.74]
 [6.84 3.21 3.17]]


In [10]:
print("Matrix B is: ")
print(b)

Matrix B is: 
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### Perform 32-bit floating point matrix multiplication

In [11]:
c = np.matmul(a, b)
print("Matrix multiplication result (c): ")
print(c)

Matrix multiplication result (c): 
[[2.54 4.31 3.15]
 [1.01 0.   5.74]
 [6.84 3.21 3.17]]


### Convert array to the 8-bit fixed point

In [25]:
a_fix = Fxp(a, signed=False, n_word=8, n_frac=4)
b_fix = Fxp(b, signed=False, n_word=8, n_frac=4)

In [29]:
print("Fixed-point representation (a_fix):")
for i in range(a_fix.shape[0]):
    for j in range(a_fix.shape[1]):
        print(a_fix[i, j].bin(frac_dot=True), end=' ')
    print()

Fixed-point representation (a_fix):
0010.1000 0100.0100 0011.0010 
0001.0000 0000.0000 0101.1011 
0110.1101 0011.0011 0011.0010 


In [28]:
print("Fixed-point representation (b_fix):")
for i in range(b_fix.shape[0]):
    for j in range(b_fix.shape[1]):
        print(b_fix[i, j].bin(frac_dot=True), end=' ')
    print()

Fixed-point representation (b_fix):
0001.0000 0000.0000 0000.0000 
0000.0000 0001.0000 0000.0000 
0000.0000 0000.0000 0001.0000 


In [31]:
c_fix = np.matmul(a_fix, b_fix)
print("Matrix multiplication result (c_fix): ")
print(c_fix)

Matrix multiplication result (c_fix): 
[[2.5    4.25   3.125 ]
 [1.     0.     5.6875]
 [6.8125 3.1875 3.125 ]]
